### ISSUE TITLE
Build failure in Dey-3.2 for latest version

### ISSUE THREAD

**Issue by krucialmike** [digi-embedded/cc_dey#1]
It looks like newer versions of this tool depend on features which are not present in `libdigiapix` in `dey-3.2`

Yocto now fails for fresh builds with the following message:
```
src/rci_state_device_info.c:20:10: fatal error: libdigiapix/process.h: No such file or directory
   20 | #include <libdigiapix/process.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Reverting to: `dc2a8a718f90e30c720f440e6879838463df6966` fixes the build.

As in `dey-3.2` `cloudconnector` is not pinned to a specific `SRCREV` this issue may occur for any users of `dey-3.2`. In our case a stable CI build started to fail.

**Comment by jviguera** [comment]
Hi @krucialmike 

Thanks for the report. We'll work on this and provide a fix as soon as possible.

**Comment by jviguera** [comment]
This has been fixed in meta-digi:

https://github.com/digi-embedded/meta-digi/commit/3233b7fdcbd6288cc2d05f1a40879850ac4bff3a
